### PR TITLE
fix: move astro to peer dependencies

### LINKED ISSUE #355: After upgrading to v0.0.4: Type 'AstroIntegration' is not assignable to type AstroIntegration
Hi. I have a problem with types after upgrading the plugin to version 0.0.4.

```
"@playform/compress": "^0.0.4",
"astro": "^4.8.3",
```

Here is a part of `astro.config.ts`:

```ts
import compress from '@playform/compress'
import { defineConfig } from 'astro/config'

export default defineConfig({
  integrations: [
    compress({
      Exclude: [
        (file: string) => file.endsWith('.png') && !file.includes('hero.'),
      ],
      Image: process.env.COMPRESS_IMAGES !== 'false',
      JavaScript: true,
      HTML: true,
      SVG: true,
    }),
  ],
  // ...
})
```

I get the following error:

```
astro.config.ts:86:5 - error TS2322: Type 'AstroIntegration' is not assignable to type 'false | AstroIntegration | (false | AstroIntegration | null | undefined)[] | null | undefined'.
  Type 'import("/Users/azat/Developer/azat-io/node_modules/.pnpm/astro@4.8.1_@types+node@20.12.11_lightningcss@1.24.1_terser@5.31.0_typescript@5.4.5/node_modules/astro/dist/@types/astro").AstroIntegration' is not assignable to type 'import("/Users/azat/Developer/azat-io/node_modules/.pnpm/astro@4.8.3_@types+node@20.12.11_lightningcss@1.24.1_terser@5.31.0_typescript@5.4.5/node_modules/astro/dist/@types/astro").AstroIntegration'.
    The types of 'hooks['astro:config:setup']' are incompatible between these types.
      Type '(options: { config: import("/Users/azat/Developer/azat-io/node_modules/.pnpm/astro@4.8.1_@types+node@20.12.11_lightningcss@1.24.1_terser@5.31.0_typescript@5.4.5/node_modules/astro/dist/@types/astro").AstroConfig; ... 11 more ...; logger: import("/Users/azat/Developer/azat-io/node_modules/.pnpm/astro@4.8.1_@types+nod...' is not assignable to type '(options: { config: import("/Users/azat/Developer/azat-io/node_modules/.pnpm/astro@4.8.3_@types+node@20.12.11_lightningcss@1.24.1_terser@5.31.0_typescript@5.4.5/node_modules/astro/dist/@types/astro").AstroConfig; ... 11 more ...; logger: import("/Users/azat/Developer/azat-io/node_modules/.pnpm/astro@4.8.3_@types+nod...'.
        Types of parameters 'options' and 'options' are incompatible.
          Type '{ config: import("/Users/azat/Developer/azat-io/node_modules/.pnpm/astro@4.8.3_@types+node@20.12.11_lightningcss@1.24.1_terser@5.31.0_typescript@5.4.5/node_modules/astro/dist/@types/astro").AstroConfig; ... 11 more ...; logger: import("/Users/azat/Developer/azat-io/node_modules/.pnpm/astro@4.8.3_@types+node@20.12.11...' is not assignable to type '{ config: import("/Users/azat/Developer/azat-io/node_modules/.pnpm/astro@4.8.1_@types+node@20.12.11_lightningcss@1.24.1_terser@5.31.0_typescript@5.4.5/node_modules/astro/dist/@types/astro").AstroConfig; ... 11 more ...; logger: import("/Users/azat/Developer/azat-io/node_modules/.pnpm/astro@4.8.1_@types+node@20.12.11...'.
            The types of 'config.integrations' are incompatible between these types.
              Type 'import("/Users/azat/Developer/azat-io/node_modules/.pnpm/astro@4.8.3_@types+node@20.12.11_lightningcss@1.24.1_terser@5.31.0_typescript@5.4.5/node_modules/astro/dist/@types/astro").AstroIntegration[]' is not assignable to type 'import("/Users/azat/Developer/azat-io/node_modules/.pnpm/astro@4.8.1_@types+node@20.12.11_lightningcss@1.24.1_terser@5.31.0_typescript@5.4.5/node_modules/astro/dist/@types/astro").AstroIntegration[]'.
                Type 'import("/Users/azat/Developer/azat-io/node_modules/.pnpm/astro@4.8.3_@types+node@20.12.11_lightningcss@1.24.1_terser@5.31.0_typescript@5.4.5/node_modules/astro/dist/@types/astro").AstroIntegration' is not assignable to type 'import("/Users/azat/Developer/azat-io/node_modules/.pnpm/astro@4.8.1_@types+node@20.12.11_lightningcss@1.24.1_terser@5.31.0_typescript@5.4.5/node_modules/astro/dist/@types/astro").AstroIntegration'.
                  The types of 'hooks['astro:build:ssr']' are incompatible between these types.
                    Type '(options: { manifest: import("/Users/azat/Developer/azat-io/node_modules/.pnpm/astro@4.8.3_@types+node@20.12.11_lightningcss@1.24.1_terser@5.31.0_typescript@5.4.5/node_modules/astro/dist/core/app/types").SerializedSSRManifest; entryPoints: Map<...>; middlewareEntryPoint: URL | undefined; logger: import("/Users/azat/...' is not assignable to type '(options: { manifest: import("/Users/azat/Developer/azat-io/node_modules/.pnpm/astro@4.8.1_@types+node@20.12.11_lightningcss@1.24.1_terser@5.31.0_typescript@5.4.5/node_modules/astro/dist/core/app/types").SerializedSSRManifest; entryPoints: Map<...>; middlewareEntryPoint: URL | undefined; logger: import("/Users/azat/...'.
                      Types of parameters 'options' and 'options' are incompatible.
                        Type '{ manifest: import("/Users/azat/Developer/azat-io/node_modules/.pnpm/astro@4.8.1_@types+node@20.12.11_lightningcss@1.24.1_terser@5.31.0_typescript@5.4.5/node_modules/astro/dist/core/app/types").SerializedSSRManifest; entryPoints: Map<...>; middlewareEntryPoint: URL | undefined; logger: import("/Users/azat/Developer/...' is not assignable to type '{ manifest: import("/Users/azat/Developer/azat-io/node_modules/.pnpm/astro@4.8.3_@types+node@20.12.11_lightningcss@1.24.1_terser@5.31.0_typescript@5.4.5/node_modules/astro/dist/core/app/types").SerializedSSRManifest; entryPoints: Map<...>; middlewareEntryPoint: URL | undefined; logger: import("/Users/azat/Developer/...'.
                          Types of property 'manifest' are incompatible.
                            Type 'import("/Users/azat/Developer/azat-io/node_modules/.pnpm/astro@4.8.1_@types+node@20.12.11_lightningcss@1.24.1_terser@5.31.0_typescript@5.4.5/node_modules/astro/dist/core/app/types").SerializedSSRManifest' is not assignable to type 'import("/Users/azat/Developer/azat-io/node_modules/.pnpm/astro@4.8.3_@types+node@20.12.11_lightningcss@1.24.1_terser@5.31.0_typescript@5.4.5/node_modules/astro/dist/core/app/types").SerializedSSRManifest' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the types of the target's properties.
                              Type 'SerializedSSRManifest' is not assignable to type 'Omit<SSRManifest, "assets" | "middleware" | "routes" | "componentMetadata" | "inlinedScripts" | "clientDirectives">' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the types of the target's properties.
                                The types returned by 'pageModule.page()' are incompatible between these types.
                                  Type 'Promise<import("/Users/azat/Developer/azat-io/node_modules/.pnpm/astro@4.8.1_@types+node@20.12.11_lightningcss@1.24.1_terser@5.31.0_typescript@5.4.5/node_modules/astro/dist/@types/astro").ComponentInstance>' is not assignable to type 'Promise<import("/Users/azat/Developer/azat-io/node_modules/.pnpm/astro@4.8.3_@types+node@20.12.11_lightningcss@1.24.1_terser@5.31.0_typescript@5.4.5/node_modules/astro/dist/@types/astro").ComponentInstance>'.
                                    Type 'import("/Users/azat/Developer/azat-io/node_modules/.pnpm/astro@4.8.1_@types+node@20.12.11_lightningcss@1.24.1_terser@5.31.0_typescript@5.4.5/node_modules/astro/dist/@types/astro").ComponentInstance' is not assignable to type 'import("/Users/azat/Developer/azat-io/node_modules/.pnpm/astro@4.8.3_@types+node@20.12.11_lightningcss@1.24.1_terser@5.31.0_typescript@5.4.5/node_modules/astro/dist/@types/astro").ComponentInstance' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the types of the target's properties.
                                      The types returned by 'default(...)' are incompatible between these types.
                                        Type 'import("/Users/azat/Developer/azat-io/node_modules/.pnpm/astro@4.8.1_@types+node@20.12.11_lightningcss@1.24.1_terser@5.31.0_typescript@5.4.5/node_modules/astro/dist/runtime/server/render/astro/factory").AstroFactoryReturnValue | Promise<...>' is not assignable to type 'import("/Users/azat/Developer/azat-io/node_modules/.pnpm/astro@4.8.3_@types+node@20.12.11_lightningcss@1.24.1_terser@5.31.0_typescript@5.4.5/node_modules/astro/dist/runtime/server/render/astro/factory").AstroFactoryReturnValue | Promise<...>'.
                                          Type 'RenderTemplateResult' is not assignable to type 'AstroFactoryReturnValue | Promise<AstroFactoryReturnValue>'.
                                            Property '[renderTemplateResultSym]' is missing in type 'import("/Users/azat/Developer/azat-io/node_modules/.pnpm/astro@4.8.1_@types+node@20.12.11_lightningcss@1.24.1_terser@5.31.0_typescript@5.4.5/node_modules/astro/dist/runtime/server/render/astro/render-template").RenderTemplateResult' but required in type 'import("/Users/azat/Developer/azat-io/node_modules/.pnpm/astro@4.8.3_@types+node@20.12.11_lightningcss@1.24.1_terser@5.31.0_typescript@5.4.5/node_modules/astro/dist/runtime/server/render/astro/render-template").RenderTemplateResult'
```

### PR DESCRIPTION
**Pull request by azat-io**
Close #355

This fix works for me.

### CODE REVIEW

File: package.json [hunk 1]
```diff
@@ -52,7 +51,11 @@
 		"terser": "5.31.0"
 	},
 	"devDependencies": {
-		"@playform/build": "0.0.10"
+		"@playform/build": "0.0.10",
+		"astro": "4.10.0"
+	},
+	"peerDependencies": {
+		"astro": "^4.10.0"
```
Comment (bennycode) [inline package.json]: How about turning this into a wildcard to allow all possible Astro transformer definitions?

```suggestion
		"astro": "*"
```

Comment (azat-io) [reply package.json]: I think it's safer to support only minor and patch versions?

**Comment by azat-io** [comment]
Rebased

File: package.json (hunk 1 above)
Comment (NikolaRHristov) [reply package.json]: Will adding `astro` to `devDependencies` and `peerDependencies` solve for future versions of `astro` as well ?

For example which version will `npm` select during a normal `npm install` if there's an `astro` 5.10 and in `peerDependencies` we have `astro` `^4.10` but for the `devDependencies` we still use `4.10`.

Also I think this - https://github.com/PlayForm/Compress/pull/370/files#r1630294340 is a good suggestion, as it may match the `astro` version correctly and allow for backwards compatibility, however, still unsure. That's why we have `@playform/adapt` - https://github.com/PlayForm/Adapt in development but it's still early stages.

Comment (azat-io) [reply package.json]: Yes.
It supports Astro v4.x.x

I don't think it's a good idea to support Astro 5, as there may be changes there that will change the plugins API.

The best solution would be to leave it as is. With caret.

Comment (NikolaRHristov) [reply package.json]: What I'm wondering is if we leave it as is:

```json
{
	"devDependencies": {
		"@playform/build": "0.0.10",
		"astro": "4.10.0"
	},
	"peerDependencies": {
		"astro": "^4.10.0"
	}
}
```

and a new version comes out, say `4.20` or `4.30`. Will that break because we still use `astro` `4.10.0` in the `devDependencies` and which `peerDependencies` versions will get selected and installed alongside `astro-compress`?

Can you test this with a lower version?

For example have a `package.json` with:

```json
{
	"devDependencies": {
		"@playform/build": "0.0.10",
		"astro": "4.3.5"
	},
	"peerDependencies": {
		"astro": "^4.3.5"
	}
}
```

and test it with an `astro` installation of `4.10.1`. This is what I'm wondering.

Comment (NikolaRHristov) [reply package.json]: So I've issued new versions of `astro-compress` [v2.2.27](https://github.com/PlayForm/Compress/releases/tag/AstroCompress%2Fv2.2.27) and `@playform/compress` [v0.0.12](https://github.com/PlayForm/Compress/releases/tag/Compress%2Fv0.0.12) that should address this using the `astro` `*` wildcard version. Can you give it a go ? I've tested locally and it seems to install the correct version used in the parent `astro` installation.

**Review by NikolaRHristov — APPROVED** [review]
